---
- name: Install Java
  yum:
    name: "{{ java_version }}"  # Adjust the package name for your distribution
    state: present
    #when: ansible_os_family == 'RedHat'

- name: Set JAVA_HOME environment variable on client machine
  lineinfile:
    dest: /home/ansible/.bashrc  # Replace with the appropriate shell configuration file (e.g., .bashrc, .zshrc)
    line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'  # Adjust the path as needed for your Java version
    insertafter: EOF
    #when: ansible_distribution == 'RedHat'

- name: Ensure Tomcat user exists
  ansible.builtin.user:
    name: tomcat
    home: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    system: yes
    shell: /bin/nologin

- name: Download Tomcat 7
  copy:
    src: "/home/ansible/Playbooks/without-role/tomcat-java-installation-ansible/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
  register: download_result

- name: Extract Tomcat archive
  ansible.builtin.unarchive:
    src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_install_dir }}"
    remote_src: yes
  when: download_result.changed

- name: Change ownership of Tomcat directory
  file:
    path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes
    state: directory

- name: Set JAVA_HOME environment variable in Tomcat file
  lineinfile:
    dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/catalina.sh"
    regexp: '^#.*JAVA_HOME.*$'
    line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
  environment:
    JAVA_HOME: "{{ lookup('env','JAVA_HOME') }}"
    #when: ansible_os_family == 'RedHat'

- name: Set Tomcat environment variables
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'CATALINA_HOME="{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"'
  when: download_result.changed

- name: Creating a service file
  copy:
    content: |-
      [Unit]
      Description=Tomcat Service
      Requires=network.target
      After=network.target
      [Service]
      Type=forking
      User=tomcat
      Environment="CATALINA_PID=/opt/apache-tomcat-7.0.109/logs/tomcat.pid"
      Environment="CATALINA_BASE=/opt/apache-tomcat-7.0.109"
      Environment="CATALINA_HOME=/opt/apache-tomcat-7.0.109"
      Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
      ExecStart=/opt/apache-tomcat-7.0.109/bin/startup.sh
      ExecStop=/opt/apache-tomcat-7.0.109/bin/shutdown.sh
      Restart=on-abnormal
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/tomcat.service

- name: Reload the SystemD to re-read configurations
  systemd:
    daemon-reload: yes

- name: Enable the tomcat service and start
  ansible.builtin.systemd:
    name: tomcat
    enabled: yes
    state: started

- name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
  uri:
    url: http://localhost:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10

- name: Download Maven version {{maven_version}}
  copy:
    src: "/home/ansible/Playbooks/without-role/tomcat-java-installation-ansible/apache-maven-{{maven_version}}-bin.tar.gz"
    dest: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz"
  register: mvn_download_result

- name: Extract Maven  archive
  ansible.builtin.unarchive:
    src: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_install_dir }}"
    remote_src: yes
  when: mvn_download_result.changed
  
- name: Remove the downloaded tar file for Maven version {{maven_version}}
  file:
    path: "{{ maven_install_dir }}/apache-maven-{{ maven_version }}-bin.tar.gz"
    state: absent

- name: Set MVN_HOME environment variable on client machine
  lineinfile:
    dest: "/home/ansible/.bashrc"
    line: 'export MVN_HOME={{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin'
    insertafter: EOF

- name: Create maven.sh inside /etc/profile.d
  file:
    path: /etc/profile.d/maven.sh
    state: touch

- name: Add maven.sh in /etc.profile.d
  ansible.builtin.lineinfile:
    path: /etc/profile.d/maven.sh
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_items: 
    - "export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk"
    - "export M2_HOME={{ maven_install_dir }}/apache-maven-{{ maven_version }}"
    - "export MAVEN_HOME={{ maven_install_dir }}/apache-maven-{{ maven_version }}"
    - "export PATH=${M2_HOME}/bin:${PATH}"

- name: Create a project folder
  file:
    path: "{{git_repo_dir}}"
    state: directory

- name: Clone Git repository
  git:
    repo: https://github.com/AshviniChavan2904/tomcat-java-project.git
    dest: "{{git_repo_dir}}"

- name: Running mvn clean package
  shell: "/opt/apache-maven-3.8.8/bin/mvn clean package"
  register: mvn_result
  args:
    chdir: "{{git_repo_dir}}"

- name: Maven clean task output
  debug:
    var: mvn_result.stdout_lines

- name: Stop tomcat service
  service:
    name: tomcat
    state: stopped

- name: Find war files
  find:
    paths: "/opt/apache-tomcat-7.0.109/webapps/"
    patterns: "*.war"
  register: file_output

- name: Create a backup directory
  file:
    path: "/opt/war_backup_dir/bkp_{{ansible_date_time.date}}"
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0755
    recurse: true

- name: Take backup of war file
  copy:
    src: "{{item.path}}"
    dest: "/opt/war_backup_dir/bkp_{{ansible_date_time.date}}"
    remote_src: true
  with_items: "{{file_output.files}}"

- name: Remove previous war file
  file:
    path: "{{item.path}}"
    state: absent
  with_items: "{{file_output.files}}"

- name: Deploy war file in tomcat
  copy:
    src: "{{git_repo_dir}}/target/my-webapp.war"
    dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps"
    owner: tomcat
    group: tomcat
    mode: 0755
    remote_src: true

- name: Start tomcat service
  service:
    name: tomcat
    state: started

- name: Get the tomcat service status
  command: systemctl status tomcat
  register: tomcat_status

- name: Print service status
  debug:
    msg: "{{tomcat_status.stdout_lines[2]}}"
