---
- name: Install openjdk-8-jdk & Tomcat 7 on RHEL 9
  hosts: tomcat
  gather_facts: true
  vars: 
          java_version: java-1.8.0-openjdk-devel.x86_64   # Change to the desired OpenJDK version   
          tomcat_version_dir: 7                         # Change to the desired Tomcat version download directory
          tomcat_version: 7.0.109                         # Change to the desired Tomcat 7 version
          tomcat_install_dir: /opt                        # Change to the desired installation directory
          maven_version: 3.8.8
          maven_install_dir: /opt
          git_repo_dir: /home/ansible/git_projects
  tasks:
        - name: Ensure Tomcat user exists
          ansible.builtin.user:
            name: tomcat
            home: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
            system: yes
            shell: /bin/nologin

        - name: Download Tomcat 7
          copy:
            src: "./apache-tomcat-{{ tomcat_version }}.tar.gz"
            dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
          register: download_result

        - name: Extract Tomcat archive
          ansible.builtin.unarchive:
            src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
            dest: "{{ tomcat_install_dir }}"
            remote_src: yes
          when: download_result.changed

        - name: Change ownership of Tomcat directory
          file:
            path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"
            owner: tomcat
            group: tomcat
            mode: "u+rwx,g+rx,o=rx"
            recurse: yes
            state: directory

        - name: Set JAVA_HOME environment variable in Tomcat file
          lineinfile:
            dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/bin/catalina.sh"
            regexp: '^#.*JAVA_HOME.*$'
            line: 'export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk'
          environment:
            JAVA_HOME: "{{ lookup('env','JAVA_HOME') }}"

        - name: Set Tomcat environment variables
          ansible.builtin.lineinfile:
            path: /etc/environment
            line: 'CATALINA_HOME="{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}"'
          when: download_result.changed

        - name: Creating a service file
          copy:
            content: |-
              [Unit]
              Description=Tomcat Service
              Requires=network.target
              After=network.target
              [Service]
              Type=forking
              User=tomcat
              Environment="CATALINA_PID=/opt/apache-tomcat-7.0.109/logs/tomcat.pid"
              Environment="CATALINA_BASE=/opt/apache-tomcat-7.0.109"
              Environment="CATALINA_HOME=/opt/apache-tomcat-7.0.109"
              Environment="CATALINA_OPTS=-Xms512M -Xmx1024M -server -XX:+UseParallelGC"
              ExecStart=/opt/apache-tomcat-7.0.109/bin/startup.sh
              ExecStop=/opt/apache-tomcat-7.0.109/bin/shutdown.sh
              Restart=on-abnormal
              [Install]
              WantedBy=multi-user.target
            dest: /etc/systemd/system/tomcat.service

        - name: Reload the SystemD to re-read configurations
          systemd:
            daemon-reload: yes

        - name: Edit tomcat-users.xml
          lineinfile:
            path: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml"
            insertbefore: "^</tomcat-users>"
            line: "{{item}}"
            state: present
          with_items:
            - '<role rolename="admin-gui" />'
            - '<role rolename="manager-gui" />'
            - '<user username="admin" password="Admin@123" roles="admin-gui, manager-gui" />'

        - name: Take backup of context.xml
          copy: 
            src: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml" 
            dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml_{{ ansible_date_time.date }}_{{ansible_date_time.time | regex_replace(':','')}}"
            owner: tomcat
            group: tomcat
            mode: 0755
            remote_src: true

        - name: Copy context.xml to META-INF
          copy:
            src: "./context.xml"
            dest: "{{ tomcat_install_dir }}/apache-tomcat-{{ tomcat_version }}/webapps/manager/META-INF/context.xml"
            owner: tomcat
            group: tomcat
            mode: 0755

        - name: Enable the tomcat service and start
          ansible.builtin.systemd:
            name: tomcat
            enabled: yes
            state: started

        - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
          uri:
            url: http://localhost:8080
          register: result
          until: "result.status == 200"
          retries: 5
          delay: 10
